name: README build

on:
  push:
    branches:
      - master
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - run: npm install
      - run: node index.js
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git add .
      - run: git commit -m "generated"
      - run: git push
